//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_HVK_TTCD1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cay()
        {
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int Id { get; set; }
        public string Tencay { get; set; }
        public int Iddanhmuc { get; set; }
        public int Soluong { get; set; }
        public decimal Dongia { get; set; }
        public string Hinhanh { get; set; }
        public bool Trangthai { get; set; }
    
        public virtual DanhMucCay DanhMucCay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
    }
}
