//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_HVK_TTCD1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucCay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucCay()
        {
            this.Cays = new HashSet<Cay>();
        }
    
        public int Id { get; set; }
        public string Tendanhmuc { get; set; }
        public bool Trangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cay> Cays { get; set; }
    }
}
